name: Build distribution

on: [push, pull_request]

jobs:
 build:
   runs-on: ubuntu-20.04

   steps:
    - 
      name: Warmup GitHub Actions
      uses: actions/checkout@v2.0.0
    - 
      name: Install and setup Emscripten
      uses: mymindstorm/setup-emsdk@ca0cef33e53bf9149891246a1b13ef3dbd498ca5
    - 
      name: Setup Node.js
      uses: actions/setup-node@v2.2.0
    -
      name: Install packages for the tools
      run: 
        (cd tools/fetch-latest-lua-version && npm install)
        (cd tools/scrape-lua-signatures && npm install)
    - 
      name: Build latest Lua version to Web Assembly using Emscripten
      run: make all
    - 
      name: Publish to GitHub pages
      uses: crazy-max/ghaction-github-pages@db4476a01402e1a7ce05f41832040eef16d14925
      with:
        target_branch: gh-pages
        build_dir: docs/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
