name: Build distribution

on: [push, pull_request]

jobs:
 build:
   runs-on: ubuntu-20.04

   steps:
    - 
      name: Warmup GitHub Actions
      uses: actions/checkout@v2.0.0
    - 
      name: Install and setup Emscripten
      uses: mymindstorm/setup-emsdk@ca0cef33e53bf9149891246a1b13ef3dbd498ca5
    - 
      name: Build Lua Web Assembly using Emscripten
      run: make all
